# Generated by Django 2.2.12 on 2022-04-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fyi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E_language', models.CharField(max_length=50, verbose_name='语言简写')),
                ('C_language', models.CharField(max_length=70, verbose_name='语言')),
            ],
            options={
                'db_table': 'fyi_language',
            },
        ),
    ]
